// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7RXYgJwJojA5de0o2TQ4vVry_XFCAPjE',
    appId: '1:20290572587:web:fae8dc2c04e0115becb56e',
    messagingSenderId: '20290572587',
    projectId: 'ktu-yemekhane',
    authDomain: 'ktu-yemekhane.firebaseapp.com',
    storageBucket: 'ktu-yemekhane.firebasestorage.app',
    measurementId: 'G-W648XFT012',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClnIsTumfipmlkzJD3PIOxyOvX04FmlXM',
    appId: '1:20290572587:android:2c776dbbf3929adcecb56e',
    messagingSenderId: '20290572587',
    projectId: 'ktu-yemekhane',
    storageBucket: 'ktu-yemekhane.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuB0rmKwlG051iwSAOPTjiPPNHjhJr8Jk',
    appId: '1:20290572587:ios:883546fdd3263651ecb56e',
    messagingSenderId: '20290572587',
    projectId: 'ktu-yemekhane',
    storageBucket: 'ktu-yemekhane.firebasestorage.app',
    iosBundleId: 'com.example.yemekTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuB0rmKwlG051iwSAOPTjiPPNHjhJr8Jk',
    appId: '1:20290572587:ios:883546fdd3263651ecb56e',
    messagingSenderId: '20290572587',
    projectId: 'ktu-yemekhane',
    storageBucket: 'ktu-yemekhane.firebasestorage.app',
    iosBundleId: 'com.example.yemekTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7RXYgJwJojA5de0o2TQ4vVry_XFCAPjE',
    appId: '1:20290572587:web:bae2f430aa58c049ecb56e',
    messagingSenderId: '20290572587',
    projectId: 'ktu-yemekhane',
    authDomain: 'ktu-yemekhane.firebaseapp.com',
    storageBucket: 'ktu-yemekhane.firebasestorage.app',
    measurementId: 'G-VHNHWFJCDR',
  );
}
